Blog/Blog.UI/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.BLL;
using Blog.MODELS;

namespace Blog.UI.Controllers
{
    public class BlogController : Controller
    {

        // GET: Blog
        public ActionResult Index()
        {
            var blogOp = new BlogOperations();

            var fullblogs = blogOp.GetAllBlogEntries().Where(m => m.EndDate > DateTime.Now || m.EndDate.HasValue == false).ToList();

            //fullblogs.Count

            return View(fullblogs);
        }

        //Create Get Static action, with partial view
        public PartialViewResult GetStaticPages()
        {
            var blogOp = new BlogOperations();
            var staticPages = blogOp.GetStaticEntries();

            return PartialView(staticPages);

        }

        // GET: Blog/Details/5
        public ActionResult Details(int id)
        {
            var blogOp = new BlogOperations();

            return View(blogOp.GetBlogEntry(id));
        }

        // GET: Blog/Create
        public ActionResult Create()
        {
            var blogEntry = new BlogEntry();
            return View(blogEntry);
        }

        // POST: Blog/Create
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(BlogEntry blogEntry)
        {
            try
            {
                var blogOp = new BlogOperations();

                if (User.IsInRole("Admin"))
                {
                    blogEntry.StatusID = 1;
                }
                else
                {
                    blogEntry.StatusID = 3;
                }

                blogOp.CreateBlogEntry(blogEntry);



                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Blog/Edit/5
        public ActionResult Edit(int id)
        {
            var blogOp = new BlogOperations();

            return View(blogOp.GetBlogEntry(id));
        }

        // POST: Blog/Edit/5
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Edit(int id, BlogEntry blogEntry)
        {
            try
            {
                var blogOp = new BlogOperations();
                blogOp.EditBlogEntry(blogEntry);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Blog/Delete/5
        public ActionResult Delete(int id)
        {
            var blogOp = new BlogOperations();

            return View(blogOp.GetBlogEntry(id));
        }

        // POST: Blog/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, BlogEntry blogEntry)
        {
            try
            {
                var blogOp = new BlogOperations();
                blogOp.DeleteBlogEntry(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult BlogSummary()
        {
            return View();
        }

        public ActionResult Blogs()
        {
            var operations = new BlogOperations();


            return View(operations.GetAllBlogEntries());
        }

        //GET: Blog/CreateStatic
        public ActionResult CreateStatic()
        {
            var staticEntry = new StaticEntry();
            return View(staticEntry);
        }

        //POST: Blog/CreateStatic
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult CreateStatic(StaticEntry staticEntry)
        {
            try
            {
                var blogOp = new BlogOperations();

                blogOp.CreateStaticEntry(staticEntry);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //GET: Blog/DeleteStatic
        public ActionResult DeleteStatic(int id)
        {
            var blogOp = new BlogOperations();

            return View(blogOp.GetStaticEntry(id));
        }

        //POST: Blog/DeleteStatic
        [HttpPost]
        public ActionResult DeleteStatic(int id, StaticEntry staticEntry)
        {
            try
            {
                var blogOp = new BlogOperations();
                blogOp.DeleteStaticEntry(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //GET: Blog/EditStatic
        public ActionResult EditStatic(int id)
        {
            var blogOp = new BlogOperations();

            return View(blogOp.GetStaticEntry(id));
        }

        //POST: Blog/EditStatic
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult EditStatic(int id, StaticEntry staticEntry)
        {
            try
            {
                var blogOp = new BlogOperations();
                blogOp.EditStaticEntry(staticEntry);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult GetStaticPage(int id)
        {
            var blogOp = new BlogOperations();
            var getentry = blogOp.GetStaticEntry(id);

            return View(getentry);


        }
    }
}

Blog/Blog.UI/Views/Shared/_Layout.cshtml
@using Blog.UI.Controllers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


</head>
<body ng-controller="RootController">
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Sarah's Blog", "Index", "Blog", new {area = ""}, new {@class = "navbar-brand"})
        </div>

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

                <li>@Html.ActionLink("Home", "Index", "Blog")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                @{ Html.RenderAction("GetStaticPages", "Blog"); }

            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
<div class="container body-content" role="main">
    @RenderBody()
    <footer>Sarah's Tech Blog 2015</footer>
</div>

@Scripts.Render("~/bundles/jquery")
<script src="~/Scripts/tinymce/tinymce.js"></script>
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>

</html>